### ISSUE TITLE
dataset downloading link is not working

### ISSUE THREAD

**Issue by ayesha-119** [declare-lab/multimodal-deep-learning#6]
the google drive link you have provided is not working. its showing 404 error. kindly check it out and is there any other source available to download the CMU-MOSEI dataset

**Comment by soujanyaporia** [comment]
The link worked for me: https://drive.google.com/drive/folders/17ZYaqRVWd0e5Atd14TPyAN76EywCyiJi

**Comment by YAMY1234** [comment]
> The link worked for me: https://drive.google.com/drive/folders/17ZYaqRVWd0e5Atd14TPyAN76EywCyiJi

Thansks for sharing link of CMU-MOSEI. Cause Official SDK provided for CMU-MOSEI and CMU-MOSI cannot work recently    : ( . Do you have google driver or other sharing links of CMU-MOSI. Begging for that also TvT

**Comment by soujanyaporia** [comment]
Please find everything here: https://drive.google.com/drive/folders/1djN_EkrwoRLUt7Vq_QfNZgCl_24wBiIK

**Comment by YAMY1234** [comment]
Thanks very much for your links provided.




YAMY
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "declare-lab/multimodal-deep-learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月5日(星期六) 晚上7:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [declare-lab/multimodal-deep-learning] dataset downloading link is not working (Issue #6)





 
Please find everything here: https://drive.google.com/drive/folders/1djN_EkrwoRLUt7Vq_QfNZgCl_24wBiIK

**Comment by ayesha-119** [comment]
> The link worked for me: https://drive.google.com/drive/folders/17ZYaqRVWd0e5Atd14TPyAN76EywCyiJi

Thank you for providing the link. It works now
